// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages-nerocash.proto

package trezor

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// *
// Request: Ask device for public key corresponding to address_n path
// @start
// @next NeroCashPublicKey
// @next Failure
type NeroCashGetPublicKey struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	ShowDisplay          *bool    `protobuf:"varint,2,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashGetPublicKey) Reset()         { *m = NeroCashGetPublicKey{} }
func (m *NeroCashGetPublicKey) String() string { return proto.CompactTextString(m) }
func (*NeroCashGetPublicKey) ProtoMessage()    {}
func (*NeroCashGetPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{0}
}

func (m *NeroCashGetPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashGetPublicKey.Unmarshal(m, b)
}
func (m *NeroCashGetPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashGetPublicKey.Marshal(b, m, deterministic)
}
func (m *NeroCashGetPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashGetPublicKey.Merge(m, src)
}
func (m *NeroCashGetPublicKey) XXX_Size() int {
	return xxx_messageInfo_NeroCashGetPublicKey.Size(m)
}
func (m *NeroCashGetPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashGetPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashGetPublicKey proto.InternalMessageInfo

func (m *NeroCashGetPublicKey) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *NeroCashGetPublicKey) GetShowDisplay() bool {
	if m != nil && m.ShowDisplay != nil {
		return *m.ShowDisplay
	}
	return false
}

// *
// Response: Contains public key derived from device private seed
// @end
type NeroCashPublicKey struct {
	Node                 *HDNodeType `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Xpub                 *string     `protobuf:"bytes,2,opt,name=xpub" json:"xpub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NeroCashPublicKey) Reset()         { *m = NeroCashPublicKey{} }
func (m *NeroCashPublicKey) String() string { return proto.CompactTextString(m) }
func (*NeroCashPublicKey) ProtoMessage()    {}
func (*NeroCashPublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{1}
}

func (m *NeroCashPublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashPublicKey.Unmarshal(m, b)
}
func (m *NeroCashPublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashPublicKey.Marshal(b, m, deterministic)
}
func (m *NeroCashPublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashPublicKey.Merge(m, src)
}
func (m *NeroCashPublicKey) XXX_Size() int {
	return xxx_messageInfo_NeroCashPublicKey.Size(m)
}
func (m *NeroCashPublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashPublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashPublicKey proto.InternalMessageInfo

func (m *NeroCashPublicKey) GetNode() *HDNodeType {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *NeroCashPublicKey) GetXpub() string {
	if m != nil && m.Xpub != nil {
		return *m.Xpub
	}
	return ""
}

// *
// Request: Ask device for NeroCash address corresponding to address_n path
// @start
// @next NeroCashAddress
// @next Failure
type NeroCashGetAddress struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	ShowDisplay          *bool    `protobuf:"varint,2,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashGetAddress) Reset()         { *m = NeroCashGetAddress{} }
func (m *NeroCashGetAddress) String() string { return proto.CompactTextString(m) }
func (*NeroCashGetAddress) ProtoMessage()    {}
func (*NeroCashGetAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{2}
}

func (m *NeroCashGetAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashGetAddress.Unmarshal(m, b)
}
func (m *NeroCashGetAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashGetAddress.Marshal(b, m, deterministic)
}
func (m *NeroCashGetAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashGetAddress.Merge(m, src)
}
func (m *NeroCashGetAddress) XXX_Size() int {
	return xxx_messageInfo_NeroCashGetAddress.Size(m)
}
func (m *NeroCashGetAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashGetAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashGetAddress proto.InternalMessageInfo

func (m *NeroCashGetAddress) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *NeroCashGetAddress) GetShowDisplay() bool {
	if m != nil && m.ShowDisplay != nil {
		return *m.ShowDisplay
	}
	return false
}

// *
// Response: Contains an NeroCash address derived from device private seed
// @end
type NeroCashAddress struct {
	AddressBin           []byte   `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"`
	AddressHex           *string  `protobuf:"bytes,2,opt,name=addressHex" json:"addressHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashAddress) Reset()         { *m = NeroCashAddress{} }
func (m *NeroCashAddress) String() string { return proto.CompactTextString(m) }
func (*NeroCashAddress) ProtoMessage()    {}
func (*NeroCashAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{3}
}

func (m *NeroCashAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashAddress.Unmarshal(m, b)
}
func (m *NeroCashAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashAddress.Marshal(b, m, deterministic)
}
func (m *NeroCashAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashAddress.Merge(m, src)
}
func (m *NeroCashAddress) XXX_Size() int {
	return xxx_messageInfo_NeroCashAddress.Size(m)
}
func (m *NeroCashAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashAddress proto.InternalMessageInfo

func (m *NeroCashAddress) GetAddressBin() []byte {
	if m != nil {
		return m.AddressBin
	}
	return nil
}

func (m *NeroCashAddress) GetAddressHex() string {
	if m != nil && m.AddressHex != nil {
		return *m.AddressHex
	}
	return ""
}

// *
// Request: Ask device to sign transaction
// All fields are optional from the protocol's point of view. Each field defaults to value `0` if missing.
// Note: the first at most 1024 bytes of data MUST be transmitted as part of this message.
// @start
// @next NeroCashTxRequest
// @next Failure
type NeroCashSignTx struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Nonce                []byte   `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice" json:"gas_price,omitempty"`
	GasLimit             []byte   `protobuf:"bytes,4,opt,name=gas_limit,json=gasLimit" json:"gas_limit,omitempty"`
	ToBin                []byte   `protobuf:"bytes,5,opt,name=toBin" json:"toBin,omitempty"`
	ToHex                *string  `protobuf:"bytes,11,opt,name=toHex" json:"toHex,omitempty"`
	Value                []byte   `protobuf:"bytes,6,opt,name=value" json:"value,omitempty"`
	DataInitialChunk     []byte   `protobuf:"bytes,7,opt,name=data_initial_chunk,json=dataInitialChunk" json:"data_initial_chunk,omitempty"`
	DataLength           *uint32  `protobuf:"varint,8,opt,name=data_length,json=dataLength" json:"data_length,omitempty"`
	ChainId              *uint32  `protobuf:"varint,9,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	TxType               *uint32  `protobuf:"varint,10,opt,name=tx_type,json=txType" json:"tx_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashSignTx) Reset()         { *m = NeroCashSignTx{} }
func (m *NeroCashSignTx) String() string { return proto.CompactTextString(m) }
func (*NeroCashSignTx) ProtoMessage()    {}
func (*NeroCashSignTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{4}
}

func (m *NeroCashSignTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashSignTx.Unmarshal(m, b)
}
func (m *NeroCashSignTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashSignTx.Marshal(b, m, deterministic)
}
func (m *NeroCashSignTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashSignTx.Merge(m, src)
}
func (m *NeroCashSignTx) XXX_Size() int {
	return xxx_messageInfo_NeroCashSignTx.Size(m)
}
func (m *NeroCashSignTx) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashSignTx.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashSignTx proto.InternalMessageInfo

func (m *NeroCashSignTx) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *NeroCashSignTx) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *NeroCashSignTx) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *NeroCashSignTx) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *NeroCashSignTx) GetToBin() []byte {
	if m != nil {
		return m.ToBin
	}
	return nil
}

func (m *NeroCashSignTx) GetToHex() string {
	if m != nil && m.ToHex != nil {
		return *m.ToHex
	}
	return ""
}

func (m *NeroCashSignTx) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *NeroCashSignTx) GetDataInitialChunk() []byte {
	if m != nil {
		return m.DataInitialChunk
	}
	return nil
}

func (m *NeroCashSignTx) GetDataLength() uint32 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

func (m *NeroCashSignTx) GetChainId() uint32 {
	if m != nil && m.ChainId != nil {
		return *m.ChainId
	}
	return 0
}

func (m *NeroCashSignTx) GetTxType() uint32 {
	if m != nil && m.TxType != nil {
		return *m.TxType
	}
	return 0
}

// *
// Response: Device asks for more data from transaction payload, or returns the signature.
// If data_length is set, device awaits that many more bytes of payload.
// Otherwise, the signature_* fields contain the computed transaction signature. All three fields will be present.
// @end
// @next NeroCashTxAck
type NeroCashTxRequest struct {
	DataLength           *uint32  `protobuf:"varint,1,opt,name=data_length,json=dataLength" json:"data_length,omitempty"`
	SignatureV           *uint32  `protobuf:"varint,2,opt,name=signature_v,json=signatureV" json:"signature_v,omitempty"`
	SignatureR           []byte   `protobuf:"bytes,3,opt,name=signature_r,json=signatureR" json:"signature_r,omitempty"`
	SignatureS           []byte   `protobuf:"bytes,4,opt,name=signature_s,json=signatureS" json:"signature_s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashTxRequest) Reset()         { *m = NeroCashTxRequest{} }
func (m *NeroCashTxRequest) String() string { return proto.CompactTextString(m) }
func (*NeroCashTxRequest) ProtoMessage()    {}
func (*NeroCashTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{5}
}

func (m *NeroCashTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashTxRequest.Unmarshal(m, b)
}
func (m *NeroCashTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashTxRequest.Marshal(b, m, deterministic)
}
func (m *NeroCashTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashTxRequest.Merge(m, src)
}
func (m *NeroCashTxRequest) XXX_Size() int {
	return xxx_messageInfo_NeroCashTxRequest.Size(m)
}
func (m *NeroCashTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashTxRequest proto.InternalMessageInfo

func (m *NeroCashTxRequest) GetDataLength() uint32 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

func (m *NeroCashTxRequest) GetSignatureV() uint32 {
	if m != nil && m.SignatureV != nil {
		return *m.SignatureV
	}
	return 0
}

func (m *NeroCashTxRequest) GetSignatureR() []byte {
	if m != nil {
		return m.SignatureR
	}
	return nil
}

func (m *NeroCashTxRequest) GetSignatureS() []byte {
	if m != nil {
		return m.SignatureS
	}
	return nil
}

// *
// Request: Transaction payload data.
// @next NeroCashTxRequest
type NeroCashTxAck struct {
	DataChunk            []byte   `protobuf:"bytes,1,opt,name=data_chunk,json=dataChunk" json:"data_chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashTxAck) Reset()         { *m = NeroCashTxAck{} }
func (m *NeroCashTxAck) String() string { return proto.CompactTextString(m) }
func (*NeroCashTxAck) ProtoMessage()    {}
func (*NeroCashTxAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{6}
}

func (m *NeroCashTxAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashTxAck.Unmarshal(m, b)
}
func (m *NeroCashTxAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashTxAck.Marshal(b, m, deterministic)
}
func (m *NeroCashTxAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashTxAck.Merge(m, src)
}
func (m *NeroCashTxAck) XXX_Size() int {
	return xxx_messageInfo_NeroCashTxAck.Size(m)
}
func (m *NeroCashTxAck) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashTxAck.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashTxAck proto.InternalMessageInfo

func (m *NeroCashTxAck) GetDataChunk() []byte {
	if m != nil {
		return m.DataChunk
	}
	return nil
}

// *
// Request: Ask device to sign message
// @start
// @next NeroCashMessageSignature
// @next Failure
type NeroCashSignMessage struct {
	AddressN             []uint32 `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashSignMessage) Reset()         { *m = NeroCashSignMessage{} }
func (m *NeroCashSignMessage) String() string { return proto.CompactTextString(m) }
func (*NeroCashSignMessage) ProtoMessage()    {}
func (*NeroCashSignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{7}
}

func (m *NeroCashSignMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashSignMessage.Unmarshal(m, b)
}
func (m *NeroCashSignMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashSignMessage.Marshal(b, m, deterministic)
}
func (m *NeroCashSignMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashSignMessage.Merge(m, src)
}
func (m *NeroCashSignMessage) XXX_Size() int {
	return xxx_messageInfo_NeroCashSignMessage.Size(m)
}
func (m *NeroCashSignMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashSignMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashSignMessage proto.InternalMessageInfo

func (m *NeroCashSignMessage) GetAddressN() []uint32 {
	if m != nil {
		return m.AddressN
	}
	return nil
}

func (m *NeroCashSignMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// *
// Response: Signed message
// @end
type NeroCashMessageSignature struct {
	AddressBin           []byte   `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	AddressHex           *string  `protobuf:"bytes,3,opt,name=addressHex" json:"addressHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashMessageSignature) Reset()         { *m = NeroCashMessageSignature{} }
func (m *NeroCashMessageSignature) String() string { return proto.CompactTextString(m) }
func (*NeroCashMessageSignature) ProtoMessage()    {}
func (*NeroCashMessageSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{8}
}

func (m *NeroCashMessageSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashMessageSignature.Unmarshal(m, b)
}
func (m *NeroCashMessageSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashMessageSignature.Marshal(b, m, deterministic)
}
func (m *NeroCashMessageSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashMessageSignature.Merge(m, src)
}
func (m *NeroCashMessageSignature) XXX_Size() int {
	return xxx_messageInfo_NeroCashMessageSignature.Size(m)
}
func (m *NeroCashMessageSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashMessageSignature.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashMessageSignature proto.InternalMessageInfo

func (m *NeroCashMessageSignature) GetAddressBin() []byte {
	if m != nil {
		return m.AddressBin
	}
	return nil
}

func (m *NeroCashMessageSignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *NeroCashMessageSignature) GetAddressHex() string {
	if m != nil && m.AddressHex != nil {
		return *m.AddressHex
	}
	return ""
}

// *
// Request: Ask device to verify message
// @start
// @next Success
// @next Failure
type NeroCashVerifyMessage struct {
	AddressBin           []byte   `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Message              []byte   `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	AddressHex           *string  `protobuf:"bytes,4,opt,name=addressHex" json:"addressHex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeroCashVerifyMessage) Reset()         { *m = NeroCashVerifyMessage{} }
func (m *NeroCashVerifyMessage) String() string { return proto.CompactTextString(m) }
func (*NeroCashVerifyMessage) ProtoMessage()    {}
func (*NeroCashVerifyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb33f46ba915f15c, []int{9}
}

func (m *NeroCashVerifyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeroCashVerifyMessage.Unmarshal(m, b)
}
func (m *NeroCashVerifyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeroCashVerifyMessage.Marshal(b, m, deterministic)
}
func (m *NeroCashVerifyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeroCashVerifyMessage.Merge(m, src)
}
func (m *NeroCashVerifyMessage) XXX_Size() int {
	return xxx_messageInfo_NeroCashVerifyMessage.Size(m)
}
func (m *NeroCashVerifyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NeroCashVerifyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NeroCashVerifyMessage proto.InternalMessageInfo

func (m *NeroCashVerifyMessage) GetAddressBin() []byte {
	if m != nil {
		return m.AddressBin
	}
	return nil
}

func (m *NeroCashVerifyMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *NeroCashVerifyMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *NeroCashVerifyMessage) GetAddressHex() string {
	if m != nil && m.AddressHex != nil {
		return *m.AddressHex
	}
	return ""
}

func init() {
	proto.RegisterType((*NeroCashGetPublicKey)(nil), "hw.trezor.messages.nerocash.NeroCashGetPublicKey")
	proto.RegisterType((*NeroCashPublicKey)(nil), "hw.trezor.messages.nerocash.NeroCashPublicKey")
	proto.RegisterType((*NeroCashGetAddress)(nil), "hw.trezor.messages.nerocash.NeroCashGetAddress")
	proto.RegisterType((*NeroCashAddress)(nil), "hw.trezor.messages.nerocash.NeroCashAddress")
	proto.RegisterType((*NeroCashSignTx)(nil), "hw.trezor.messages.nerocash.NeroCashSignTx")
	proto.RegisterType((*NeroCashTxRequest)(nil), "hw.trezor.messages.nerocash.NeroCashTxRequest")
	proto.RegisterType((*NeroCashTxAck)(nil), "hw.trezor.messages.nerocash.NeroCashTxAck")
	proto.RegisterType((*NeroCashSignMessage)(nil), "hw.trezor.messages.nerocash.NeroCashSignMessage")
	proto.RegisterType((*NeroCashMessageSignature)(nil), "hw.trezor.messages.nerocash.NeroCashMessageSignature")
	proto.RegisterType((*NeroCashVerifyMessage)(nil), "hw.trezor.messages.nerocash.NeroCashVerifyMessage")
}

func init() { proto.RegisterFile("messages-nerocash.proto", fileDescriptor_cb33f46ba915f15c) }

var fileDescriptor_cb33f46ba915f15c = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9b, 0xb4, 0x49, 0x26, 0x0d, 0x1f, 0xa6, 0x55, 0x17, 0x0a, 0x34, 0x18, 0x21, 0xe5,
	0x00, 0x3e, 0x70, 0x43, 0xe2, 0xd2, 0x52, 0x44, 0x2b, 0x4a, 0x55, 0xdc, 0xa8, 0x57, 0x6b, 0x63,
	0x6f, 0xe3, 0x55, 0x9d, 0xdd, 0xe0, 0x5d, 0xb7, 0x0e, 0x7f, 0x82, 0x23, 0xff, 0x87, 0x5f, 0x86,
	0xf6, 0x2b, 0x71, 0x52, 0x54, 0x0e, 0xbd, 0x65, 0xde, 0xbc, 0x7d, 0xf3, 0x66, 0xf4, 0x62, 0xd8,
	0x99, 0x10, 0x21, 0xf0, 0x98, 0x88, 0x77, 0x44, 0x66, 0xa4, 0x20, 0xe5, 0x24, 0x9c, 0x16, 0x5c,
	0x72, 0x7f, 0x37, 0xbb, 0x09, 0x65, 0x41, 0x7e, 0xf2, 0x22, 0x74, 0x94, 0xd0, 0x51, 0x9e, 0x6d,
	0xcf, 0x5f, 0x25, 0x7c, 0x32, 0xe1, 0xcc, 0xbc, 0x09, 0x2e, 0x60, 0xeb, 0xb3, 0xa5, 0x7c, 0x21,
	0xf2, 0xac, 0x1c, 0xe5, 0x34, 0xf9, 0x4a, 0x66, 0xfe, 0x2e, 0x74, 0x70, 0x9a, 0x16, 0x44, 0x88,
	0x98, 0x21, 0xaf, 0xdf, 0x18, 0xf4, 0xa2, 0xb6, 0x05, 0x4e, 0xfd, 0x57, 0xb0, 0x29, 0x32, 0x7e,
	0x13, 0xa7, 0x54, 0x4c, 0x73, 0x3c, 0x43, 0x6b, 0x7d, 0x6f, 0xd0, 0x8e, 0xba, 0x0a, 0x3b, 0x34,
	0x50, 0x30, 0x82, 0xc7, 0x4e, 0x77, 0x21, 0xfa, 0x01, 0x9a, 0x8c, 0xa7, 0x04, 0x79, 0x7d, 0x6f,
	0xd0, 0x7d, 0xff, 0x26, 0xfc, 0x87, 0x5f, 0x6b, 0xee, 0xe8, 0xf0, 0x94, 0xa7, 0x64, 0x38, 0x9b,
	0x92, 0x48, 0x3f, 0xf1, 0x7d, 0x68, 0x56, 0xd3, 0x72, 0xa4, 0x47, 0x75, 0x22, 0xfd, 0x3b, 0x18,
	0x82, 0x5f, 0xf3, 0xbe, 0x6f, 0xdc, 0xdd, 0xdb, 0xf9, 0x77, 0x78, 0xe8, 0x54, 0x9d, 0xe4, 0x4b,
	0x00, 0xab, 0x70, 0x40, 0x99, 0x76, 0xbf, 0x19, 0xd5, 0x90, 0x5a, 0xff, 0x88, 0x54, 0xd6, 0x62,
	0x0d, 0x09, 0xfe, 0xac, 0xc1, 0x03, 0xa7, 0x79, 0x4e, 0xc7, 0x6c, 0x58, 0xdd, 0xed, 0x72, 0x0b,
	0xd6, 0x19, 0x67, 0x09, 0xd1, 0x52, 0x9b, 0x91, 0x29, 0xd4, 0x93, 0x31, 0x16, 0xf1, 0xb4, 0xa0,
	0x09, 0x41, 0x0d, 0xdd, 0x69, 0x8f, 0xb1, 0x38, 0x53, 0xb5, 0x6b, 0xe6, 0x74, 0x42, 0x25, 0x6a,
	0xce, 0x9b, 0x27, 0xaa, 0x56, 0x7a, 0x92, 0x2b, 0xeb, 0xeb, 0x46, 0x4f, 0x17, 0x06, 0x55, 0x86,
	0xbb, 0xda, 0xb0, 0x29, 0x14, 0x7a, 0x8d, 0xf3, 0x92, 0xa0, 0x0d, 0xc3, 0xd5, 0x85, 0xff, 0x16,
	0xfc, 0x14, 0x4b, 0x1c, 0x53, 0x46, 0x25, 0xc5, 0x79, 0x9c, 0x64, 0x25, 0xbb, 0x42, 0x2d, 0x4d,
	0x79, 0xa4, 0x3a, 0xc7, 0xa6, 0xf1, 0x49, 0xe1, 0xfe, 0x1e, 0x74, 0x35, 0x3b, 0x27, 0x6c, 0x2c,
	0x33, 0xd4, 0xee, 0x7b, 0x83, 0x5e, 0x04, 0x0a, 0x3a, 0xd1, 0x88, 0xff, 0x14, 0xda, 0x49, 0x86,
	0x29, 0x8b, 0x69, 0x8a, 0x3a, 0xba, 0xdb, 0xd2, 0xf5, 0x71, 0xea, 0xef, 0x40, 0x4b, 0x56, 0xb1,
	0x9c, 0x4d, 0x09, 0x02, 0xdd, 0xd9, 0x90, 0x95, 0xca, 0x41, 0xf0, 0xdb, 0x5b, 0x44, 0x6a, 0x58,
	0x45, 0xe4, 0x47, 0x49, 0x84, 0x5c, 0x1d, 0xe5, 0xdd, 0x1a, 0xb5, 0x07, 0x5d, 0x41, 0xc7, 0x0c,
	0xcb, 0xb2, 0x20, 0xf1, 0xb5, 0xbe, 0x68, 0x2f, 0x82, 0x39, 0x74, 0xb1, 0x4c, 0x28, 0xec, 0x61,
	0x17, 0x84, 0x68, 0x99, 0x20, 0xec, 0x71, 0x17, 0x84, 0xf3, 0x20, 0x84, 0xde, 0xc2, 0xd8, 0x7e,
	0x72, 0xe5, 0xbf, 0x00, 0xed, 0xc0, 0x5e, 0xc9, 0xe4, 0xa5, 0xa3, 0x10, 0x7d, 0x9e, 0xe0, 0x04,
	0x9e, 0xd4, 0xd3, 0xf0, 0xcd, 0x64, 0xff, 0xee, 0x48, 0x20, 0x68, 0xd9, 0xff, 0x88, 0x0d, 0x85,
	0x2b, 0x83, 0x0a, 0x90, 0x53, 0xb3, 0x4a, 0xe7, 0xce, 0xda, 0x7f, 0x83, 0xfb, 0x1c, 0x3a, 0xf3,
	0x3d, 0xac, 0xee, 0x02, 0x58, 0x89, 0x75, 0xe3, 0x56, 0xac, 0x7f, 0x79, 0xb0, 0xed, 0x46, 0x5f,
	0x90, 0x82, 0x5e, 0xce, 0xdc, 0x2a, 0xf7, 0x9b, 0x5b, 0xdb, 0xb5, 0xb1, 0xb4, 0xeb, 0x8a, 0xa3,
	0xe6, 0xaa, 0xa3, 0x83, 0x8f, 0xf0, 0x3a, 0xe1, 0x93, 0x50, 0x60, 0xc9, 0x45, 0x46, 0x73, 0x3c,
	0x12, 0xee, 0x03, 0x93, 0xd3, 0x91, 0xf9, 0xe2, 0x8d, 0xca, 0xcb, 0x83, 0xed, 0xa1, 0x06, 0xad,
	0x5b, 0xb7, 0xc2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xce, 0x81, 0xc8, 0x59, 0x05, 0x00,
	0x00,
}
